# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title a Gibbs sampler using Rcpp
#' @description a Gibbs sampler using Rcpp, which comes from my homework 10.
#' @param inix the initial value of the markov chain
#' @param iniy the initial value of the markov chain
#' @param mu1 the mean of X of the target distribution
#' @param mu2 the mean of Y of the target distribution
#' @param sigma1 the standard deviation of X of the target distribution
#' @param sigma2 the standard deviation of Y of the target distribution
#' @param rho the correlation between X and Y of the target distribution
#' @param n the quantity of samples would like to generate, with initial 10000
#' @param burn the quantity of samples dropped before the chain go to steady
#' @return a random sample of size \code{n+burn}
#' @examples
#' \dontrun{
#' temp = gibbsC(100, 10, 0, 0, 1, 1, 0.9)[-(1:1000), ]
#' par(mfrow=c(2,1));
#' plot(temp[-(1:1000),1],type='l')
#' plot(temp[-(1:1000),2],type='l')
#' }
#' @export
gibbsC <- function(inix, iniy, mu1, mu2, sigma1, sigma2, rho, n = 10000L, burn = 1000L) {
    .Call('_StatComp22005_gibbsC', PACKAGE = 'StatComp22005', inix, iniy, mu1, mu2, sigma1, sigma2, rho, n, burn)
}

